### ISSUE TITLE
apply_conditioning

### ISSUE THREAD

**Issue by retroactively** [Zzl35/flow-to-better#1]
```
in modes/utils.py
def apply_conditioning(x, conditions, observation_dim):
    # x[:, 0: 1, :observation_dim] = conditions
    return x
```

what it means?

**Comment by Zzl35** [comment]
Our code refers to the [decision diffuser](https://github.com/anuragajay/decision-diffuser), which is a clean and elegant implementation of diffusion models for trajectory generation. Originally, this function was intended to ensure that the initial state of the trajectory generated by the diffusion model aligns with the conditions, where the condition should also be an observation. However, since flow-to-better generates full trajectories at once, this constraint is not necessary. Therefore, we have commented out the initial state constraint of this function. Thank you for reporting this, we will check and optimize the code soon!

**Comment by retroactively** [comment]
Thank you for your thoughtful reply.
